create table currency
(
    id         bigint generated by default as identity primary key,
    buy_price  numeric,
    sell_price numeric,
    name       varchar not null,
    avatar_id  integer
);

create table currency_price
(
    id         bigint generated by default as identity primary key,
    price      numeric   not null,
    currency   varchar   not null,

    created_at TIMESTAMP NOT NULL DEFAULT current_timestamp
);

insert into currency (name)
values ('RUB'),
       ('USD'),
       ('EUR'),
       ('BTC');
